import type { Metadata } from "next";
import { Geist, Geist_Mono, Anek_Devanagari } from "next/font/google";
import NavBar from "@/components/nav-bar";
import Footer from "@/components/footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anekDevanagari = Anek_Devanagari({
  variable: "--font-anek-devanagari",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anekDevanagari.variable} antialiased`}
      >
        <div className="bg-dots min-h-screen flex items-center justify-center bg-white text-black w-full font-sans">
          <div className="w-full">
            <NavBar />
            <main className="mt-16 md:mt-20">
              {children}
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
